version: 0.2
env:
  variables:
    SHELL: "/bin/bash"
phases:
  build:
    commands:
      - yum -y install findutils
      - chmod +x scripts/package.sh
      - mvn clean install
      - cat scripts/package.sh
      - scripts/package.sh
artifacts:
  files:
  - '**/*'
